### ISSUE TITLE
테스트용 목 데이터 배열이 import 시 에러 발생상황

### ISSUE THREAD

**Issue by akdl911215** [akdl911215/calendar-front#33]
테스트용 목 데이터 배열이 import 해서 사용할 때 읽을 수 없다는 에러가 발생.
<br>

![Image](https://github.com/akdl911215/calendar-front/assets/76759835/034c6835-e3b8-4e00-b606-6c267175b613)

<br>
 위 부분에 대한 문제 해결시 해결방법 공유하기

**Comment by NEARworld** [comment]
`npm start -- --reset-cache`

제 생각에는 `babel.config.js` 파일이 환경 설정 파일이라 캐싱되어 있었던거 같아요. 그래서 저희가 `babel.config.js` 를 수정해줘도 이전에 이미 캐싱된 애를 계속 사용하고 있었고요..

캐싱된거 지우고 다시 하니 되네요.
